version: '3.8'

services:
  resume-builder:
    container_name: resume-builder-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - APP_URL=http://localhost:3000
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium
    restart: unless-stopped
